config/routes.rb
Rails.application.routes.draw do
  scope :admin do
    resources :states
    resources :conversations
    resources :codes
    resources :participants, except: %i[new]
    resources :participations
    resources :admins
    resources :api_calls
    resources :roles
    resources :winners
    resources :prizes
    resources :whatsapp_campaigns, only: %i[index], as: 'enviar_mensajes'
    get 'whatsapp_campaigns_data', to: 'whatsapp_campaigns#whatsapp_campaigns_data'
    root to: 'dashboard#index'
    get 'dashboard' => 'dashboard#dashboard', as: 'dashboard'
    post 'sorteo' => 'winners#sorteo', as: 'sorteo_winner_post'
    get 'sorteo' => 'winners#sorteo', as: 'sorteo_winner'
    get 'sorteo_config' => 'winners#sorteo_config', as: 'sorteo_config'
    get 'sorteo_count', to: 'winners#sorteo_count'
  end

  devise_for :admins, skip: %i[registrations passwords]

  scope :whatsapp do
    get 'webhook' => 'whatsapp#webhook'
    post 'webhook' => 'whatsapp#webhook'

    post 'whatsapp_campaigns', to: 'whatsapp_campaigns#create', as: 'whatsapp_campaigns'
  end

  root to: 'site#index', as: 'site_index'

  get 'check_winner' => 'winners#check', as: 'check_winner'
  post 'check_winner' => 'winners#check', as: 'check_winner_post'
  get 'confirm_winner/:id' => 'winners#confirm', as: 'confirm_winner'
  get 'draw_winner' => 'winners#draw', as: 'draw_winner'
  post 'draw_winner' => 'winners#draw', as: 'draw_winner_post'
  patch 'admin/sort' => 'admins#sort', as: 'admin_sort'
  get 'participation/:new_status/:id' => 'participations#change_status', as: 'participation_approve'
end

app/views/admins/_form.html.erb
                                    <% if admin.errors.any? %>
                                        <div class="alert alert-danger alert-dismissible" role="alert">
                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                        <div class="alert-message">
                                            <strong>Error.</strong> No pudo guardarse debido a los siguientes errores
                                        </div>
                                        </div>
                                    <% end %>

                                    <div class="mb-3">
                                        <%= form.label :role_id, class: 'form-label' %>
                                        <%= form.select :role_id, Role.all.collect { |c| [c.name, c.id] }, {include_blank: true}, class: 'form-select' %>
                                    </div>

                                    <div class="mb-3">
                                        <%= form.label :email, class: 'form-label' %>
                                        <%= form.text_field :email, class: 'form-control' %>
                                    </div>

                                    <div class="mb-3">
                                        <%= form.label :password, class: 'form-label' %>
                                        <%= form.password_field :password, class: 'form-control' %>
                                    </div>

                                    <div class="mb-3">
                                        <%= form.label :password_confirmation, class: 'form-label' %>
                                        <%= form.password_field :password_confirmation, class: 'form-control' %>
                                    </div>

                                    <div class="actions">
                                        <%= button_tag( :class => "btn btn-primary mt-2") do %>
                                        <i class="fas fa-fw fa-save"></i> Guardar
                                        <% end %>
                                    </div>

app/views/admins/edit.html.erb
<div class="row">
  <div class="col-12 col-lg-5">
    <div class="mb-3">
      <h1 class="h3 d-inline align-middle">Editando administrador</h1>
    </div>
    <div class="card">
      <div class="card-header">
        <h5 class="card-title mb-0">Editando</h5>
      </div>
      <div class="card-body">
        <%= form_with(model: @admin, url: admin_path(@admin), method: :put) do |form| %>
          <%= render 'form', admin: @admin, form: form %>
        <% end %>
      </div>
    </div>
    <%= link_to 'Volver', admins_path %>
  </div>
</div>

app/views/admins/index.html.erb
					<div class="mb-3">
						<h1 class="h3 d-inline align-middle">Administradores</h1>
					</div>

					<div class="row">
						<div class="col-xl-8">
							<div class="card">
								<div class="card-header pb-0">
									<div class="card-actions float-end">
										<div class="dropdown show">
											<a href="#" data-bs-toggle="dropdown" data-bs-display="static">
												<i class="align-middle" data-feather="more-horizontal"></i>
											</a>

											<div class="dropdown-menu dropdown-menu-end">
												<%= link_to "Nuevo", new_admin_path, class: 'dropdown-item' %>
												<%= link_to "Buscar", nil, class: 'dropdown-item', id: 'gd-do-search' %>
											</div>
										</div>
									</div>
									<h5 class="card-title mb-0">Lista de administradores del portal</h5>
								</div>

								<div class="card-body">
									<table class="table table-hover" style="width:100%">
										<thead>
											<tr>
												<th><%= icon('id') %><%= sortable 'id', 'Id' %></i></th>
												<th><%= icon('text') %><%= sortable 'email', 'Email' %></th>
												<th><%= icon('text') %>Acciones</th>
											</tr>
										</thead>
										<tbody>
                      					<% @admins.each do |admin| %>
											<tr>
												<td><%= admin.id %></td>
												<td><%= admin.email %></td>
												<td class="table-action">
                                                    <%= link_to admin_path(admin.id)  do %>
                                                        <i class="align-middle" data-feather="eye"></i>
                                                    <% end %>
                                                    <%= link_to edit_admin_path(admin)  do %>
                                                        <i class="align-middle" data-feather="edit-2"></i>
                                                    <% end %>
                                                    <%= link_to admin_path(admin.id), method: :delete, data: { confirm: 'Estás seguro?' } do %>
                                                    <i class="align-middle" data-feather="trash"></i>
                                                    <% end %>
                        						</td>
											</tr>
                      					<% end %>
										</tbody>
									</table>

									<div class="row">
										<div class="col-sm-12 col-md-5">
											<div class="dataTables_info" id="datatables-column-search-text-inputs_info" role="status" aria-live="polite">
												<%== pagy_info @pagy %>
											</div>
										</div>
										<div class="col-sm-12 col-md-7">
											<div class="dataTables_paginate paging_simple_numbers" id="datatables-column-search-text-inputs_paginate">
												<%== pagy_bootstrap_nav @pagy %>
											</div>
										</div>
									</div>

								</div>
							</div>
						</div>
					</div>

					<%= button_to(new_admin_path, class: 'btn btn-primary btn-lg', remote: false, method: :get) do %>
						<i class="fas fa-fw fa-plus"></i> Nuevo
					<% end %>

					<script>
						$( document ).ready(function() {

							const search = $('#gd-search-container');

							$( "#gd-search-close" ).click(function() {
								search.hide(350);
							});

							$( "#gd-do-search" ).click(function( event ) {
								search.show(350);
								event.preventDefault();
							});

						});

						<% if params[:q] && params[:q][:searchable_content_cont] %>
							$('#q_searchable_content_cont').val('<%= params[:q][:searchable_content_cont] %>');
						<% end %>

					</script>

app/views/admins/new.html.erb
<div class="row">
  <div class="col-12 col-lg-5">
    <div class="mb-3">
      <h1 class="h3 d-inline align-middle">Nuevo administrador</h1>
    </div>
    <div class="card">
      <div class="card-header">
        <h5 class="card-title mb-0">Nuevo</h5>
      </div>
      <div class="card-body">
        <%= form_with(model: @admin, url: admins_path) do |form| %>
          <%= render 'form', admin: @admin, form: form %>
        <% end %>
      </div>
    </div>
    <%= link_to 'Volver', admins_path %>
  </div>
</div>

app/views/admins/show.html.erb
					<div class="mb-3">
						<h1 class="h3 d-inline align-middle">Usuario administrador</h1>
					</div>

          			<div class="row">
						<div class="col-xl-6">
							<div class="card">
								<div class="card-body">

									<table class="table table-hover table-striped table-sm mt-2 mb-6">
										<tbody>
											<tr>
												<th><%= icon('id') %>Id</th>
												<td><%= @admin.id %></td>
											</tr>
											<tr>
												<th><%= icon('text') %>Email</th>
												<td><%= @admin.email %></td>
											</tr>
											<tr>
												<th><%= icon('text') %>Password</th>
												<td><i>[no visible]</i></td>
											</tr>
										</tbody>
									</table>

								</div>
							</div>
						</div> 

         			 </div>     

          <%= link_to(admins_path, class: 'btn btn-primary btn-lg') do %>
            <i class="fas fa-fw fa-arrow-left"></i> Volver a la lista
          <% end %>

          <%= link_to(edit_admin_path(@admin), class: 'btn btn-primary btn-lg') do %>
            <i class="fas fa-fw fa-pen"></i> Editar
          <% end %>          