config/routes.rb
Rails.application.routes.draw do
  scope :admin do
    resources :states
    resources :conversations
    resources :codes
    resources :participants, except: %i[new]
    resources :participations
    resources :admins
    resources :api_calls
    resources :roles
    resources :winners
    resources :prizes
    resources :whatsapp_campaigns, only: %i[index], as: 'enviar_mensajes'
    get 'whatsapp_campaigns_data', to: 'whatsapp_campaigns#whatsapp_campaigns_data'
    root to: 'dashboard#index'
    get 'dashboard' => 'dashboard#dashboard', as: 'dashboard'
    post 'sorteo' => 'winners#sorteo', as: 'sorteo_winner_post'
    get 'sorteo' => 'winners#sorteo', as: 'sorteo_winner'
    get 'sorteo_config' => 'winners#sorteo_config', as: 'sorteo_config'
    get 'sorteo_count', to: 'winners#sorteo_count'
  end

  devise_for :admins, skip: %i[registrations passwords]

  scope :whatsapp do
    get 'webhook' => 'whatsapp#webhook'
    post 'webhook' => 'whatsapp#webhook'

    post 'whatsapp_campaigns', to: 'whatsapp_campaigns#create', as: 'whatsapp_campaigns'
  end

  root to: 'site#index', as: 'site_index'

  get 'check_winner' => 'winners#check', as: 'check_winner'
  post 'check_winner' => 'winners#check', as: 'check_winner_post'
  get 'confirm_winner/:id' => 'winners#confirm', as: 'confirm_winner'
  get 'draw_winner' => 'winners#draw', as: 'draw_winner'
  post 'draw_winner' => 'winners#draw', as: 'draw_winner_post'
  patch 'admin/sort' => 'admins#sort', as: 'admin_sort'
  get 'participation/:new_status/:id' => 'participations#change_status', as: 'participation_approve'
end

app/views/shared/_admin_index_table.html.erb
<% title        ||= 'Listado' %>
<% columns      ||= [] %>
<% records      ||= [] %>
<% q            ||= nil %>
<% new_path     ||= nil %>
<% export_path  ||= nil %>
<% record_path  ||= ->(r) { '#' } %>
<% pagy         ||= nil %>

<div class="mb-3">
  <h1 class="h3 d-inline align-middle"><%= title %></h1>
</div>
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-header pb-0">
        <div class="card-actions float-end">
          <div class="dropdown show">
            <a href="#" data-bs-toggle="dropdown" data-bs-display="static">
              <i class="align-middle" data-feather="more-horizontal"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-end">
              <% if new_path %>
                <%= link_to "Nuevo", new_path, class: 'dropdown-item' %>
              <% end %>
              <%= link_to "Buscar", nil, class: 'dropdown-item', id: 'gd-do-search' %>
              <% if export_path %>
                <%= link_to "Exportar a Excel", export_path, class: 'dropdown-item exportExcel' %>
              <% end %>
            </div>
          </div>
        </div>
        <h5 class="card-title mb-0">Lista</h5>
      </div>

      <div id="gd-search-container" class="card-header pb-0 gd-admin-search<%= " gd-display-none" if !params[:commit] %>">
        <%= search_form_for q, class: 'row row-cols-md-auto align-items-center' do |f| %>
          <% if q&.object&.respond_to?(:searchable_content) %>
            <div class="col-12">
              <%= f.label :searchable_content_cont, class: 'visually-hidden' %>
              <%= f.search_field :searchable_content_cont, class: 'form-control mb-2 me-sm-2' %>
            </div>
          <% end %>
          <div class="col-12">
            <div class="select-tag">
              Mostrar <%= select_tag :limit, options_for_select([5, 10, 25, 50, 100, 1000], params[:limit] || 10) %> registros por página
            </div>
          </div>
          <div class="col-12">
            <%= f.submit 'Buscar', class: 'btn btn-primary mb-2' %>
            <i id="gd-search-close" class="fas fa-fw fa-window-close ms-2"></i>
            <%= link_to "Limpiar", request.path %>
          </div>
        <% end %>
      </div>

      <div class="card-body">
        <table class="table table-hover" style="width:100%">
          <thead>
            <tr>
              <% columns.each do |col| %>
                <th><%= col[:header] %></th>
              <% end %>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% records.each do |record| %>
              <tr>
                <% columns.each do |col| %>
                  <td><%= col[:value].call(record) %></td>
                <% end %>
                <td class="table-action">
                  <%= link_to record_path.call(record) do %>
                    <i class="align-middle" data-feather="eye"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <% if local_assigns[:pagy] %>
          <div class="row">
            <div class="col-sm-12 col-md-5">
              <%== pagy_info pagy %>
            </div>
            <div class="col-sm-12 col-md-7">
              <%== pagy_bootstrap_nav pagy %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_admin_menu.html.erb
<ul class="sidebar-nav">
  <li class="sidebar-item">
    <a href='<%= dashboard_path %>' class="sidebar-link">
      <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Panel de control</span>
    </a>
  </li>
  <li class="sidebar-header">
    Lista de acciones
  </li>
  <% if current_admin.can('participant', 'read') %>
    <li class="sidebar-item">
      <%= link_to participants_path, class: 'sidebar-link' do %>
        <%= icon 'user' %>
        <span class="align-middle">Participantes</span>
      <% end %>
    </li>
  <% end %>

  <% if current_admin.can('participation', 'read') %>
    <li class="sidebar-item">
      <%= link_to participations_path, class: 'sidebar-link' do %>
        <%= icon 'user-plus' %>
        <span class="align-middle">Participaciones</span>
      <% end %>
    </li>
  <% end %>

  <% if current_admin.can('state', 'read') %>
    <li class="sidebar-item">
      <%= link_to states_path, class: 'sidebar-link' do %>
        <%= icon 'map-pin' %>
        <span class="align-middle">Departamentos</span>
      <% end %>
    </li>
  <% end %>

  <% if current_admin.can('winner', 'read') %>
    <li class="sidebar-item">
      <%= link_to winners_path, class: 'sidebar-link' do %>
        <i class="align-middle me-2 fas fa-fw fa-trophy"></i>
        <span class="align-middle">Ganadores</span>
      <% end %>
    </li>  
  <% end %>

  <% if current_admin.can('prize', 'read') %>
    <li class="sidebar-item">
      <%= link_to prizes_path, class: 'sidebar-link' do %>
        <i class="align-middle me-2 fas fa-fw fa-gift"></i>
        <span class="align-middle">Premios</span>
      <% end %>
    </li>  
  <% end %>

  <% if current_admin.can('winner', 'create') %>
    <li class="sidebar-item">
      <%= link_to sorteo_winner_path, class: 'sidebar-link' do %>
        <i class="align-middle me-2 fas fa-fw fa-store"></i>
        <span class="align-middle">Sorteador</span>
      <% end %>
    </li>  
  <% end %>

  <% if current_admin.can('winner', 'create') %>
    <li class="sidebar-item">
      <%= link_to sorteo_config_path, class: 'sidebar-link' do %>
        <i class="align-middle me-2 fas fa-fw fa-cogs"></i>
        <span class="align-middle">Configurar Sorteo</span>
      <% end %>
    </li>  
  <% end %>

  <li class="sidebar-header">
    Administración
  </li>
  <% if current_admin.can('admin', 'read') %>
    <li class="sidebar-item">
      <%= link_to admins_path, class: 'sidebar-link' do %>
        <i class="align-middle me-2 fas fa-fw fa-user-lock"></i>
        <span class="align-middle">Administradores</span>
      <% end %>
    </li>
  <% end %>
  <% if current_admin.can('role', 'read') %>
    <li class="sidebar-item">
      <%= link_to roles_path, class: 'sidebar-link' do %>
        <i class="align-middle me-2 fas fa-fw fa-key"></i>
        <span class="align-middle">Roles</span>
      <% end %>
    </li>
  <% end %>
</ul>
<script>
  $(document).ready(function () {
      $(`ul.sidebar-nav li.sidebar-item a[href="${document.location.pathname}"]`).closest("li.sidebar-item").addClass('active');
  });
</script>

app/views/shared/_errors_title.html.erb
<h5>Los siguientes errores evitaron que este registro pueda ser guardado:</h5>